name: draft

on:
  - workflow_dispatch

jobs:
  draft:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Publish draft
        run: |
          tag=v$(npm run --silent version)
          gh release create $tag --draft --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
